lavalink:
  server:
    password: "password123"
    trackStuckThresholdMs: 30000
    sources:
      youtube: false
  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.1"
      repository: "https://maven.lavalink.dev/releases" # this is optional for lavalink v4.0.0-beta.5 or greater
      snapshot: false # set to true if you want to use snapshot builds (see below)
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.13.5"
      snapshot: false

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - ANDROID_VR
      - WEB
      - WEBEMBEDDED 
  lavasrc:
    sources:
      spotify: true
      applemusic: true
      ytdlp: true

    spotify:
      clientId: ""
      clientSecret: ""
      countryCode: "US"
      playlistLoadLimit: 6
      albumLoadLimit: 6
    ytdlp:
      path: "./yt-dlp"
      searchLimit: 10
logging:
  file:
    path: ./logs/

  level:
    root: INFO
    lavalink: INFO